train:
  _target_: src.datasets.DLADataset
  dir: "data/dla_dataset"
  part: "train"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.DLADataset
  dir: "data/dla_dataset"
  part: "val"
  instance_transforms: ${transforms.instance_transforms.inference}
