train:
  _target_: src.datasets.DLAOnlineDataset
  dir: "data/dla_dataset"
  part: "train"
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.DLADataset
  dir: "data/dla_dataset"
  part: "val_online"
  instance_transforms: ${transforms.instance_transforms.inference}
