train:
  mix_wav: ${transforms._downsample}
  speaker_1_wav: ${transforms._downsample}
  speaker_2_wav: ${transforms._downsample}
inference:
  mix_wav: ${transforms._downsample}
  speaker_1_wav: ${transforms._downsample}
  speaker_2_wav: ${transforms._downsample}
