_target_: src.model.AVConvTasNetModel
#num_filters: 512           # N
#filter_length: 16          # L
#bottleneck_channels: 128   # B
#conv_kernel_size: 3        # P
#num_conv_blocks: 8         # X
#num_tcn_blocks: 3          # R
