_target_: src.model.ConvTasNetModel
num_filters: 512           # N
filter_length: 16          # L (in time steps; 16/8000 = 2ms)
bottleneck_channels: 512   # B
conv_num_channels: 512     # H
conv_kernel_size: 3        # P
num_conv_blocks: 8         # X
num_tcn_blocks: 10         # R

# best parameters from our report
