_target_: src.model.ConvTasNetModel
num_filters: 512           # N
filter_length: 32          # L (in time steps; 32/16000 = 2ms)
bottleneck_channels: 128   # B
conv_num_channels: 512     # H
conv_kernel_size: 3        # P
num_conv_blocks: 8         # X
num_tcn_blocks: 3          # R

# best parameters from the paper
