defaults:
  - dataloader: conv-tasnet
  - datasets: dla-test
  - model: conv-tasnet
  - metrics: metrics
  - transforms: waveform
  - _self_
inferencer:
  device_tensors: ["mix_wav", "mix_visual"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: null # path to the pretrained model
