defaults:
  - dataloader: online
  - datasets: custom-test
  - model: av-sudo-rmrf
  - metrics: no-metrics
  - transforms: waveform-inference
  - _self_
sample_rate: 8000
inferencer:
  device_tensors: ["mix_wav", "mix_visual"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "predictions"
  seed: 1
  from_pretrained: null # path to the pretrained model
