get_spectrogram:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torchaudio.transforms.MelSpectrogram
      sample_rate: 16000
      n_fft: 600
    - _target_: src.transforms.LogStable


train:
  get_spectrogram: ${transforms.instance_transforms.get_spectrogram}
inference:
  get_spectrogram: ${transforms.instance_transforms.get_spectrogram}
