get_spectrogram:
  _target_: src.transforms.SpectrogramEncoder

train:
  get_spectrogram: ${transforms.instance_transforms.get_spectrogram}
inference:
  get_spectrogram: ${transforms.instance_transforms.get_spectrogram}
